config/routes.rb
Stranasovetov::Application.routes.draw do

  resources :rubrics

  get "/publications/:id/delete" => "publications#destroy", :as => "delete_publication"
  resources :publications do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "users/:id/delete" => "users#destroy", :as => "delete_user"
  resources :users
  
  resources :sessions

  get "about/index"

  root 'about#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :require_login, only: [:index, :create]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @publication = Publication.find(params[:publication_id])
    @comments = Comment.where("publication_id = ?", @publication.id).order("id ASC")
    @comment = Comment.new
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @publication = Publication.find(params[:publication_id])
    anonymous = User.find_by_login("anonymous")
    @comment = Comment.new(comment_params)
    if current_user
      @comment.user_id = current_user.id
    else
      @comment.user_id = anonymous.id
    end

    respond_to do |format|
      if current_user
        if @comment.save
          format.html { redirect_to publication_comments_path(@publication,@comment) }
        else
          flash[:notice] = "Ошибка! Пустой комментарий."
          format.html { redirect_to publication_comments_path(@publication,@comment) }
        end
      else
        if verify_recaptcha( :model => @comment, :message => "Неправильно ввели буквы с картинки!" ) && @comment.save
          format.html { redirect_to publication_comments_path(@publication,@comment) }
        else
          flash[:notice] = "Ошибка! Пустой комментарий или неправильные буквы с картинки."
          format.html { redirect_to publication_comments_path(@publication,@comment) }
        end
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      #@comment = Comment.find(params[:id])
      @comment = Comment.where("publication_id = ? AND id = ?", params[:publication_id], params[:id])
      if @comment.size == 0
        raise ActiveRecord::RecordNotFound
      end
      rescue ActiveRecord::RecordNotFound
        flash[:notice] = 'Комментарий не найден'
        redirect_to root_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :publication_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, :url => publication_comment_path(@publication.id,@comment)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :publication_id, :value => @publication.id %>
  <div class="field">
    <%= f.text_area :body, :cols => "80", :rows => "5" %>
  </div>
  <%= recaptcha_tags unless current_user %>
  <div class="actions">
    <%= f.submit "Добавить комментарий" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% content_for :right_col do %>
<%= render 'layouts/right_col' %>
<% end %>

<h3>Комментарии к статье <%= link_to "#{@publication.title} -->>", publication_path(@publication), :title => "нажми тут чтобы перейти к публикации" %></h3>

<% @comments.each do |comment| %>
  <div class="post">
    <div class="post_text">
      <%= comment.body %>
    </div>
    <div class="post_auvtor">
      <%= User.find(comment.user_id).fio %>
      <%= comment.updated_at.strftime("%Y:%m:%d %H:%M") %>
    </div>
  </div>
<% end %>


<div class="post">
  <%= render 'form' %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', new_publication_comment_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @comment.publication_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>