config/routes.rb
Stranasovetov::Application.routes.draw do

  resources :rubrics

  get "/publications/:id/delete" => "publications#destroy", :as => "delete_publication"
  resources :publications do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "users/:id/delete" => "users#destroy", :as => "delete_user"
  resources :users
  
  resources :sessions

  get "about/index"

  root 'about#index'

  

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :user
  validates :title, :text, presence: true
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |attr| attr[:picture].nil? && attr[:size].nil? && attr[:align].nil }, :allow_destroy => true
  serialize :rubrics, Hash
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  skip_before_action :require_login, only: [:show]
  
  def index
    @publications = Publication.where("user_id = ?", current_user).order("created_at DESC")
  end
  
  def new
    @publication = current_user.publications.new
  end
  
  def create
    @publication = current_user.publications.new(params.require(:publication).permit(:title, :text, images_attributes: [:user_id, :picture, :_destroy, :id, :size, :description, :align]))
    if @publication.save
      redirect_to @publication
    else
      render "new"
    end
  end
  
  def show
    @publication = Publication.find(params[:id])
    @images = @publication.images.where("user_id = ?", @publication.user_id).order("id ASC")
    @publication_text_arr_abzac = @publication.text.split("\r")
    @publication_text = @publication.text.gsub("\r","</p><p>\r")
  end
  
  def edit
    if current_user.group == "администратор"
      @publication = Publication.find(params[:id])
    else
      @publication = current_user.publications.find(params[:id])
    end
    @images = @publication.images.where("user_id = ?", current_user).order("id ASC")
  end
  
  def update
    if current_user.group == "администратор"
      @publication = Publication.find(params[:id])
    else
      @publication = current_user.publications.find(params[:id])
    end
    params.require(:publication).permit!
    unless params[:publication][:rubrics].nil? 
      @publication.rubrics = params[:publication][:rubrics]
    end
    #if @publication.update_attributes(params.require(:publication).permit('rubrics', :title, :text, images_attributes: [:user_id, :picture, :_destroy, :id, :size, :description, :align]))
	  if @publication.update_attributes(params[:publication])
	    redirect_to @publication
	  else
	    render "edit"
	  end
  end
  
  def destroy
    @publication = current_user.publications.find(params[:id])
    @publication.destroy
    redirect_to publications_path
  end
  
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_templates.html.erb
<% if current_user %>
<div class="col3">
  <%= link_to "Изменить", edit_publication_path(@publication) %>
  <%= link_to "Просмотреть", publication_path(@publication) %>
</div>
<% else %>
  <%= render 'layouts/right_col' %>
<% end %>

app/views/publications/edit.html.erb
<% content_for :right_col do %>
<%= render 'templates' %>
<% end %>

<h3>Редактор публикации</h3>
<div class="publication_editor">
<%= form_for @publication do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "80" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :cols => "92", :rows => "25" %>
  </p>
 
  <div class="form_box">
    <h3>Картинки:</h3>
    <script type="text/javascript">
    //<![CDATA[
    var catimg_attr_counter = <%= @images.count %> ;
    var user_id = <%= current_user.id %> ;
    //]]>
    </script>
    <div id='add_catalogimgs_block'>
      <% if @publication.images.count == 0 %>
        <% 1.times { @publication.images.build } %>
      <% end %>
      <%= f.fields_for :images do |builder| %>
        <p>
          <% if builder.object.new_record? %>
            <%= builder.hidden_field :user_id, :value => current_user.id %>
            <%= builder.file_field :picture %>
            <%= builder.text_field :size, :value => "300x250" %>
            <%= builder.select :align, [['лево', 'left'], ['право', 'right'], ['центр', 'middle']] %>
          <% else %>
            <%= builder.hidden_field :user_id, :value => current_user.id %>
            <%= image_tag builder.object.picture.url(:thumb) %>
            <%= builder.file_field :picture %>
            <%= builder.text_field :size %>
            <%= builder.select :align, [['лево', 'left'], ['право', 'right'], ['центр', 'middle']] %>
            <%= builder.check_box :_destroy %>
            <%= builder.label :_destroy, "Удалить" %>
          <% end %>
        </p>
        <hr>
      <% end %>
    </div>
    <p><a href="#" id='add_catalogimgs_link'>+ Добавить картинку</a></p>
  </div>
  <p>
    <h3>Рубрики:</h3>
    <%= f.fields_for :rubrics do |rubric| %>
      <% Rubric.all.each do |r| %>
        <%= r.name %>
        <%= rubric.check_box(r.id,{checked: true},r.name) %>
      <% end %>
    <% end %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/publications/index.html.erb
<%= link_to "Создать публикацию", new_publication_path %>
<h4 align="center">Список всех публикаций пользователя <%= current_user.fio %></h4>
<table>
  <% @publications.each do |p| %>
    <tr>
      <td><%= link_to p.title, publication_path(p) %></td>
      <td><%= p.created_at.strftime("%Y.%m.%d") %></td>
      <td><%= link_to "редактировать", edit_publication_path(p) %></td>
      <td><%= link_to "удалить", delete_publication_path(p) %></td>
    </tr>
  <% end %>
</table>

app/views/publications/new.html.erb
<h1>Новая публикация</h1>
<div class="post">
<%= form_for @publication, :url => publications_path(@publication), :html => { :multipart => true } do |f| %>

  <% if @publication.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "80" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :cols => "92", :rows => "25" %>
  </p>
 
  <div class="form_box">
    <h3>Картинки:</h3>
    <script type="text/javascript">
    //<![CDATA[
    var catimg_attr_counter = 0 ;
    var user_id = <%= current_user.id %> ;
    //]]>
    </script>
    <div id='add_catalogimgs_block'>
      <% 1.times { @publication.images.build } %>
      <%= f.fields_for :images do |builder| %>
        <%= builder.hidden_field :user_id, :value => current_user.id %>
        <%= builder.file_field :picture %><br>
        Размер: <%= builder.text_field :size, :value => "300x200", :size=>6 %><br>
        Выравнивание: <%= builder.text_field :align, :value => "left", :size=>6 %><br>
      <% end %>
    </div>
    <p><a href="#" id='add_catalogimgs_link'>+ Добавить картинку</a></p>
  </div>
  <div class="form_box">
    <div id='add_rubrucs_block'>
    </div>
    <p><a href="#" id='add_rubric_link'>+ Добавить рубрику</a></p>
  </div>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/publications/show.html.erb
<% content_for :right_col do %>
<%= render 'templates' %>
<% end %>

<div class="publ_viewer">
	<div class="publ_header">
	  <%= @publication.title %>
	</div>
	<div class="publ_time">
	  <%= @publication.created_at.strftime("%Y.%m.%d") %>
	</div>
	<div class="publ_data">
		<% img_count = 0 %>
		<% @publication_text_arr_abzac.each do |abzac|%>
			<div class="publ_abzac">
				<% if @publication.images.count > 0 %>
					<% if @images[img_count] != nil && @images[img_count].size != "1x1" %>
						<%= image_tag @images[img_count].picture.url(:medium), :size => @images[img_count].size, :align=>"#{@images[img_count].align}" %>
					<% end %>
					<% img_count += 1 %>
				<% end %>
		  	<%= abzac.html_safe %>
			</div>
			<div class="publ_abzac_clear"></div>
		<% end %>
	</div>
	<div class="publ_avtor">
	  <%= User.find(@publication.user_id).fio %>
	</div>
</div>