config/routes.rb
Stranasovetov::Application.routes.draw do

  resources :rubrics

  get "/publications/:id/delete" => "publications#destroy", :as => "delete_publication"
  resources :publications do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "users/:id/delete" => "users#destroy", :as => "delete_user"
  resources :users
  
  resources :sessions

  get "about/index"

  root 'about#index'

  

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	skip_before_action :require_login, only: [:index]
	
  def index
  	@publications = Publication.where("id > 0").order("id DESC").load
  	
  	#bashorg = Feedzirra::Feed.fetch_and_parse("http://bash.im/rss/")
    #logger.debug "bashorg.entries.first.summary = #{bashorg.entries.first.summary}"
  	#pravda = Feedzirra::Feed.fetch_and_parse("http://gazeta-pravda.ru/component/option,com_rss/feed,RSS2.0/no_html,1/")
    #logger.debug "pravda.entries.first.summary = #{pravda.entries.first.summary}"
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/index.html.erb
<% content_for :right_col do %>
<%= render 'layouts/right_col' %>
<% end %>
<% @publications.each do |p|%>
  <div class="post">
    <div class="post_header"><%= p.title %></div>
    <div class="post_text">
      <%= p.text[0..500].html_safe + "......" %>
    </div>
    <div class="post_link">
      <%= link_to "читать дальше -->>", publication_path(p), :title => "нажми тут чтобы прочесть" %>
    </div>
    <div class="post_auvtor">
      <%= link_to "Комментарии", publication_comments_path(p) %>|
      рубрика: <a href="#">новости</a>|
      автор: <%= link_to User.find(p.user_id).fio, user_path(p.user_id) %>
      дата выпуска: <a href="#"><%= p.updated_at.strftime("%Y:%m:%d %H:%M") %></a>
    </div>
  </div>
<% end %>