config/routes.rb
Stranasovetov::Application.routes.draw do

  resources :rubrics

  get "/publications/:id/delete" => "publications#destroy", :as => "delete_publication"
  resources :publications do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "users/:id/delete" => "users#destroy", :as => "delete_user"
  resources :users
  
  resources :sessions

  get "about/index"

  root 'about#index'

  

end

app/views/layouts/_left_col.html.erb
<div class="col1">
	<div><a href="/">Главная страница</a></div>
	<div class="line"></div>
	<% if current_user %>
	  <%= link_to "Мои Публикации", publications_path %>
	  <%= link_to "#{current_user.fio}, настройки", edit_user_path(current_user) %>
  	<%= link_to "Выход", logout_path %>
  	<% if current_user.group =~ /администратор/ %>
  		<div class="line"></div>
  		<p>меню администратора</p>
	  	<%= link_to "Пользователи", users_path %>
	  	<%= link_to "Рубрики", rubrics_path %>
	  <% end %>
  <% else %>
    <%= link_to "Вход", login_path %>
  <% end %>
</div>

app/views/layouts/_notice.html.erb
<% [:notice, :error, :success, :alert].each do |key| %>
  <% unless flash[key].blank? %>
  	<div class="post">
	    <p class="<%= key %>">
	      <%= flash[key] %>
	    </p>
	  </div>
  <% end%>
<% end %>

app/views/layouts/_right_col.html.erb
<div class="col3">
  <div>
    <% bashorg = Feedzirra::Feed.fetch_and_parse("http://bash.im/rss/") %>
    <h6><%= bashorg.title %></h6>
    <a href="<%= bashorg.entries.first.url %>" title="дави сюда">
      <%= bashorg.entries.first.summary.html_safe %>
    </a>
  </div>
  <div>
    <% pravda = Feedzirra::Feed.fetch_and_parse("http://gazeta-pravda.ru/component/option,com_rss/feed,RSS2.0/no_html,1/") %>
    <h6><%= pravda.title %></h6>
    <a href="<%= pravda.entries.first.url %>" title="дави сюда">
      <%= pravda.entries.first.summary.html_safe %>
    </a>
  </div>
  <div>
    <% pravda = Feedzirra::Feed.fetch_and_parse("http://gazeta-pravda.ru/component/option,com_rss/feed,RSS2.0/no_html,1/") %>
    <h6><%= pravda.entries[1].title %></h6>
    <a href="<%= pravda.entries[1].url %>" title="дави сюда">
      <%= pravda.entries[1].summary.html_safe %>
    </a>
  </div>
</div>

app/views/layouts/_top.html.erb
<div class="header">
  <div class="logo1">
    <%= image_tag "flag.jpg", :width=>210, :height=>130 %>
  </div>
  <div class="logo_name1">СТРАНА СОВЕТОВ</div>
  <div class="logo_name2">Тихорецкий район</div>
  <div class="logo_name3">
    Тихорецкое районное отделение Краснодарского краевого отделения политической партии 
    &quotКоммунистическая партия Российской Федерации&quot
  </div>
  <a href="http://www.gazeta-pravda.ru/" class="pravdalink">
    <div class="pravda">Хочешь правды?<br>Тебе сюда>></div>
  </a>
  <a href="http://kprf.ru/">
    <div class="logo2"><%= image_tag "kprflogo.jpg", :width=>130, :height=>130 %></div>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="title" content="StranaSovetov.info - Страна Советов">
  <meta name="description" content="Страна Советов">
  <meta name="keywords" content="Страна Советов">
  <title>StranaSovetov.info - Страна Советов</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery-1.10.2.min.js" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top' %>

  <div class="layout">
    <%= render 'layouts/left_col' %>
    <%= yield :right_col %>
    <div class="col2">
    
      <%= render 'layouts/notice' %>

      <%= yield %>

    </div>
  </div>
  <div class="bottom_post"></div>
  <div class="footer">Подвал</div>

</body>
</html>